on:
  push:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

name: CD

jobs:
  build:
    name: Build
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-22.04
    container: fedora:37
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          sudo dnf upgrade --refresh -y
          sudo dnf install -y meson gcc gcc-c++ clang make automake cmake kernel-devel gtk4-devel libadwaita-devel poppler-glib-devel poppler-data alsa-lib-devel desktop-file-utils
      - name: Cache
        uses: actions/cache@v3
        with:
          path: |
            _mesonbuild/cargo-home/bin/
            _mesonbuild/cargo-home/registry/index/
            _mesonbuild/cargo-home/registry/cache/
            _mesonbuild/cargo-home/git/db/
            _mesonbuild/target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: ${{ runner.os }}-cargo-
      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - name: Build
        run: |
          meson setup --prefix=/usr _mesonbuild
          meson configure -Dprofile=devel _mesonbuild
          meson compile -C _mesonbuild
      - name: Install
        run: meson install -C _mesonbuild
      - name: Test
        run: meson test -v -C _mesonbuild
      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: rnote-${{ github.sha }}
          path: _mesonbuild/rnote

  format:
    name: Format
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - name: Run cargo fmt
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check