on:
  push:
  release:
    types: [published]
  workflow_dispatch:

name: Release Windows

jobs:
  build:
    runs-on: windows-2022
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: msys2/setup-msys2@v2
        with:
          update: true
          install: | 
            git mingw-w64-x86_64-xz mingw-w64-x86_64-pkgconf mingw-w64-x86_64-gcc mingw-w64-x86_64-clang mingw-w64-x86_64-toolchain 
            mingw-w64-x86_64-autotools mingw-w64-x86_64-make mingw-w64-x86_64-cmake mingw-w64-x86_64-meson mingw-w64-x86_64-diffutils 
            mingw-w64-x86_64-desktop-file-utils mingw-w64-x86_64-appstream-glib mingw-w64-x86_64-gtk4 mingw-w64-x86_64-libadwaita 
            mingw-w64-x86_64-poppler mingw-w64-x86_64-poppler-data
      - name: Install toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable-gnu
      - name: Remove duplicate libpthread.dll
        run: |
          rm /mingw64/lib/libpthread.dll.a
        continue-on-error: true
      - name: Add cargo to PATH
        run: |
          echo "PATH=$PATH:/c/Users/$USER/.cargo/bin" > ~/.bashrc
      - name: Configure
        run: meson setup --prefix=C:/msys64/mingw64 _mesonbuild
      - name: Compile
        run: meson compile -v -C _mesonbuild
      - name: Install
        run: meson install -C _mesonbuild
