on:
    release:
        types: [published]
    workflow_dispatch:

name: Release Windows

jobs:
    build:
        runs-on: windows-2022
        permissions:
            contents: write # needed for uploading release artifact
        defaults:
            run:
                shell: msys2 {0}
        steps:
            - name: Checkout
              uses: actions/checkout@v3
            - name: Setup MSYS2
              uses: msys2/setup-msys2@v2
              with:
                  release: false
                  update: true
                  install: |
                      git mingw-w64-x86_64-xz mingw-w64-x86_64-pkgconf mingw-w64-x86_64-gcc mingw-w64-x86_64-clang mingw-w64-x86_64-toolchain
                      mingw-w64-x86_64-autotools mingw-w64-x86_64-make mingw-w64-x86_64-cmake mingw-w64-x86_64-meson mingw-w64-x86_64-diffutils
                      mingw-w64-x86_64-desktop-file-utils mingw-w64-x86_64-appstream-glib mingw-w64-x86_64-gtk4 mingw-w64-x86_64-libadwaita
                      mingw-w64-x86_64-poppler mingw-w64-x86_64-poppler-data
            - name: Remove libpthread.dll.a
              run: rm /mingw64/lib/libpthread.dll.a
              continue-on-error: true
            - name: Install toolchain
              uses: dtolnay/rust-toolchain@stable
              with:
                  toolchain: stable-gnu
            - name: Configure PATH
              run: |
                  echo "/c/Users/$USER/.cargo/bin" >> $GITHUB_PATH
                  echo "/c/Program\ Files\ \(x86\)/Inno\ Setup\ 6" >> $GITHUB_PATH
            - name: Setup
              run: meson setup --prefix=C:/msys64/mingw64 _mesonbuild
            - name: Configure
              run: meson configure -Dinstaller-name='rnote-win-installer-x86-64' _mesonbuild
            - name: Compile
              run: meson compile -C _mesonbuild
            - name: Install
              run: meson install -C _mesonbuild
            - name: Build installer
              run: meson compile build-installer -C _mesonbuild
            - name: Upload installer (Workflow Artifact)
              uses: actions/upload-artifact@v3
              with:
                  name: rnote-installer-artifact
                  path: _mesonbuild/rnote-win-installer-x86-64.exe
                  if-no-files-found: error
            - name: Upload installer (Release Asset)
              if: ${{ github.event_name == 'release' }}
              shell: powershell
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: gh release upload ${{ github.ref_name }} _mesonbuild/rnote-win-installer-x86-64.exe
